version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id 
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count : 90, period : day }
        tests:
          - unique:
              column_name : "(orders_id || '_' || pdt_id)"    
        columns:
          - name: date_date
            description: date of purchase
          - name : orders_id
            description: Id of the order also primary key 
          - name: pdt_id
            description: product id that was ordered 
          - name : revenue 
            description: the revenue of this order 
          - name:  quantity
            description: quantity of product if sold il this order       
      - name: product
        identifier: raw_gz_product
        columns : 
          - name : products_id
            description: product Id also primary key 
            tests:
                - unique
                - not_null
          - name : purchSE_PRICE
            description:  the price of the purchase             
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name : orders_id 
            description: Id of the order
            tests:
                - unique
                - not_null
          - name : shipping_fee 
            description: the shipping fee
          - name : shipping_fee_1 
            description: the shipping fee
          - name : logCost 
            description: the logistic cost
          - name : ship_cost
            description: the shipping cost 
models:
   - name: int_sales_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"
            # Intermediate #
   - name: int_orders_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
   - name: int_orders_operational
     description: operational margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: operational_margin
         description: operational_margin = margin + shipping_fee - logcost - ship_cost
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: shipping_fee
         description: the price the customer pays for shipping
       - name: logcost
         description: the cost of preparing the parcel in the distribution centre/warehouse
       - name: ship_cost
         description: shipping cost paid by Greenweez to the carrier/logistics provider