version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id 
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count : 90, period : day }
        tests:
          - unique:
              column_name : "(orders_id || '_' || pdt_id)"    
        columns:
          - name: date_date
            description: date of purchase
          - name : orders_id
            description: Id of the order also primary key 
          - name: pdt_id
            description: product id that was ordered 
          - name : revenue 
            description: the revenue of this order 
          - name:  quantity
            description: quantity of product if sold il this order       
      - name: product
        identifier: raw_gz_product
        columns : 
          - name : products_id
            description: product Id also primary key 
            tests:
                - unique
                - not_null
          - name : purchSE_PRICE
            description:  the price of the purchase             
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name : orders_id 
            description: Id of the order
            tests:
                - unique
                - not_null
          - name : shipping_fee 
            description: the shipping fee
          - name : shipping_fee_1 
            description: the shipping fee
          - name : logCost 
            description: the logistic cost
          - name : ship_cost
            description: the shipping cost 